from app.services.test_service import TestService
from app.services.material_service import MaterialService
from app.services.time_series_data_service import TimeSeriesDataService
from app.services.region_service import RegionService